repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: ['black']
        language_version: python3.11

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        additional_dependencies: ['flake8']
        language_version: python3.11
