version: '3.8'

services:
  redis:
    image: redis

  db:
    image: postgres
    env_file:
      - .env

  rq:
    build: .
    command: "python manage.py rqworker default"
    volumes:
      - .:/app
    depends_on:
      - web
    links:
      - redis


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/docker-entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    links:
      - redis


networks:
  djangonetwork:
    driver: bridge