version: '3.8'

services:
  redis:
    image: redis

  db:
    image: postgres
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: create
    image: web-image
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    links:
      - redis

  rq-worker:
    image: web-image
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    command: rq-worker-default

networks:
  djangonetwork:
    driver: bridge